title: Digital Challenge
description: Digital Challenge
author: GE China
logo: /static/img/avatar.png
github: https://github.com/sternnenhimmel
about: Digital Technology Leadership Program

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
